development:
  adapter: postgresql
  database: remote_student_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: remote_student_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: remote_student_production
  pool: 5
  timeout: 5000