# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: remotestudent_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: remotestudent_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: remotestudent_production
  pool: 5
  timeout: 5000